export const ADD__DRAGGING__ITEM = "ADD__DRAGGING__ITEM";
export const REMOVE__DRAGGING__ITEM = "REMOVE__DRAGGING__ITEM";

export const UPDATE__LIST__ITEM = "UPDATE__LIST__ITEM";
export const UPDATAE__LIST__FROM_STROAGE = "UPDATAE__LIST__FROM_STROAGE";

export const UPDATE__TASK__CHECK = "UPDATE__TASK__CHECK";
